### ISSUE TITLE
Module error due to incorrect manifest file or folder name.

### ISSUE THREAD

**Issue by fvlasie** [raynichc/helpdesk#15]
Hello,

When trying to install in Gibbon 15 I get the following error message on the Manage Modules page within Gibbon:

Module error due to incorrect manifest file or folder name.

Thank you,

FV

**Comment by raynichc** [comment]
Hello,

This is a known issue that is caused by the module's folder having the wrong name when downloaded. This is planned to be fixed in the next version, but for now this can be fixed by renaming the module's folder to "Help Desk"

Hope this helps,
Ray

**Comment by fvlasie** [comment]
Ok, great! Thank you!
