### ISSUE TITLE
Create issue results in a blank screen on submit

### ISSUE THREAD

**Issue by fvlasie** [raynichc/helpdesk#16]
Create issue results in a blank screen on submit and no issue is created on Gibbon v15.

It is stuck on this URL:

/modules/Help%20Desk/issues_createProccess.php

**Comment by raynichc** [comment]
Hi,

Could you give a few more specifics on how this happened? What did you do to encounter the issue? 

Thanks,
Ray

**Comment by fvlasie** [comment]
I am trying to create an issue on this page:

https://gibbon.spots.school/c/index.php?q=/modules/Help%20Desk/issues_create.php

Home > Help Desk > Create Issue

When I click the submit button the web page just turns pure white.

**Comment by raynichc** [comment]
I was able to recreate the issue and I have released a [new version](https://github.com/raynichc/helpdesk/releases/tag/1.1.03) of the Help Desk with the patch. I hope this fixes your problem

Thanks,
Ray

**Comment by fvlasie** [comment]
Yes that works, thank you Ray!

I will keep playing with this module, it is a really good feature!
