### ISSUE TITLE
Manage Technician Group does not load

### ISSUE THREAD

**Issue by fvlasie** [raynichc/helpdesk#17]
The Manage Technician Group page is not loading, I get the Gibbon background and header, but the content and side bar are empty and completely transparent. 

/modules/Help%20Desk/helpDesk_manageTechnicianGroup.php

Thank you!

**Comment by raynichc** [comment]
Hi,

I found and fixed the bug. Here is the [new version](https://github.com/raynichc/helpdesk/releases/tag/1.1.04). Hopefully this fixes your problems.

Thanks,
Ray

**Comment by fvlasie** [comment]
It does, thank you!
